---

- name: Install docker
  apt:
    name: docker
    update_cache: yes
  become: yes

- name: Install docker-compose
  apt:
    name: docker-compose
    update_cache: yes
  become: yes

- name: add user mod
  command: usermod -aG docker {{username}}
  become: yes